# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-06 08:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actstream', '0002_remove_action_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='actor_content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actor', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='action',
            name='actor_object_id',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
    ]
